name: New Project
title: "[Project Name]"
description: Create a new project main checklist to follow.
labels: ['new project']
assignees: 
  - Abderrahim EL H.

body: 
  - type: markdown
    attributes: 
    value: Please fill the necessary elements and check the steps that are done.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Who created the project?
      placeholder: e.g email@example.com
      value: abderrahimelhamzi.dev@gmail.com
    validation: 
      required: false
  
  - type: textarea
    id: project-goal
    attributes:
      label: What is the goal behind creating this project? 
      description: By providing the target skills to learn/improve/master.
      placeholder: Briefly explain for what reason this project is created for.
      value: e.g. Learning how to used GDB and to program in C.
    validation:
      required: True

  - type: dropdown
    id: os-host
    attributes:
      label: Host Operating System
      description: What is the operating system is used?
      options: 
        - Ubuntu 25.10
        - Windows-10
        - Other
      default: Ubuntu 25.10
    validation: 
      required: True
    
  - type: dropdown
    id: project-type
    attributes:
      label: The main type of the project
      options:
        - Template Project
        - Hardware
        - HW Functional Verification
        - Software
        - Embedded Software
        - HW/SW Co-design
        - FPGA Design
        - Scripting Tools

  - type: checkboxes
    id: project-elements
    attributes:
      label: Select the potential elements that will be present in the project.
      options:
        - Template Project
        - Hardware Design
        - Hardware Functional Verification  
        - HW Design and Verification
        - FPGA Design
        - HW/SW co-design
        - Embedded Software
        - Python Tools
        - Scripting Tools (tcl, MakeFile, bash...)
      



    